project:
  type: website
  output-dir: docs
  
website:
  title: "VSV Genomes & Geography"
  navbar:
    left:
      - href: overview.qmd
        text: Overview 
    tools:
      - icon: github
        href: https://github.com/geoepi/vs-epizootics
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

