---
title: "Overview"
format:
  html: 
    df-print: kable
    code-fold: show
    code-summary: "Hide code"
    code-overflow: wrap
    toc-title: Page Contents
    toc: true
    toc-depth: 2
    toc-location: right
    number-sections: false
    html-math-method: katex
    smooth-scroll: true
editor: source
editor_options: 
  chunk_output_type: console
---

## Load Libraries
```{r}
library(tidyverse)
library(raster)
library(terra)
library(raptr)
library(rgeos)
library(pals)
library(here)

library(INLA)
#install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
```

## Custom Functions
```{r}
source(here("./R/utilities.R"))
source_dir("./R")
```


## Get Boundaries
```{r}
domain <- vect(here("assets/domain"))

obs_stack.r <- rast(
  list(
    rast(here("assets/rf_2014.tif")),
    rast(here("assets/rf_2015.tif"))
       )
)
```

## Random Points
```{r}
sample_2014 <- as.data.frame(
  raptr::randomPoints(obs_stack.r[[1]],
                      n = 600, prob = TRUE)) %>%
  mutate(year = 2014,
         set = "sim")

sample_2015 <- as.data.frame(
  raptr::randomPoints(obs_stack.r[[2]],
                      n = 900, prob = TRUE)) %>%
  mutate(year = 2015,
         set = "sim")
```

## View 
```{r}
join_sims <- rbind(sample_2014, sample_2015)

plot_rast_panels(obs_stack.r, domain, join_sims, brewer.ylorbr(4))
```

## Spatial Triangulation  
```{r}
hull <- st_convex_hull(
  st_buffer(
    st_union(
      st_as_sf(domain)),
    100))

dom_bnds <- inla.sp2segment(as(hull, "Spatial"))

set.seed(1976)
mesh.dom <- inla.mesh.2d(boundary = dom_bnds, 
                        loc = join_sims[,c("x","y")],
                        cutoff = 20, 
                        max.edge = c(60, 300),
                        offset = c(100,250),
                        min.angle = 30) 

mesh.dom$n
plot(mesh.dom, 
     draw.vertices = TRUE,
     vertex.color = c("gray60"), lwd=1.5)
```

## Node Coordinates
```{r}
dd = as.data.frame(cbind(mesh.dom$loc[,1], 
                         mesh.dom$loc[,2]))

names(dd) = c("x", "y")

dd$set <- "node"

head(dd)
```

## Copy to Year
```{r}
sample_2014 <- rbind(sample_2014, mutate(dd, year = 2014)) %>%
  mutate(
    pred_var = rnorm(n = n(), mean = 0, sd = 1),
    obs = ifelse(set == "node", 0, 1)
  )

sample_2015 <- rbind(sample_2015, mutate(dd, year = 2015)) %>%
  mutate(
    pred_var = rnorm(n = n(), mean = 0.5, sd = 1),
    obs = ifelse(set == "node", 0, 1)
  )

head(sample_2015)
```


## Cluster Distance
```{r warning=FALSE}
# 2014
split_factor <- as.factor(sample_2014$set)

NN <- as.data.frame(
  spatstat.geom::nndist(sample_2014[,c("x","y")], by = split_factor, k = 1)
)["sim"]

sample_2014$NN <- round(NN$sim, 0)



# 2015
split_factor <- as.factor(sample_2015$set)

NN <- as.data.frame(
  spatstat.geom::nndist(sample_2015[,c("x","y")], by = split_factor, k = 1)
)["sim"]

sample_2015$NN <- round(NN$sim, 0)

range(sample_2015$NN)
```


## Combine Data
```{r}
combined_data = rbind(sample_2014, sample_2015)
```

## Exposure
```{r}
host_pop.r <- rast(here("assets/host_pop.tif"))

combined_data$host_pop <- extract(host_pop.r, combined_data[,c("x","y")])[,"host_pop"]
combined_data$host_pop[is.na(combined_data$host_pop)] <- mean(combined_data$host_pop, na.rm=TRUE)

range(combined_data$host_pop)
```


## Time Step
```{r}
combined_data$time_step <- as.integer(as.factor(combined_data$year))
```

## Split Pred Variable
```{r}
combined_data <- combined_data %>%
  mutate(pred_var_14 = if_else(year == 2014, pred_var, NA),
         pred_var_15 = if_else(year == 2015, pred_var, NA))
```



## Projection  

### Random Field
```{r}
k = length(unique(combined_data$time_step))

locs = cbind(combined_data$x, combined_data$y)

A.pf = inla.spde.make.A(mesh.dom, 
                          alpha = 2,
                          loc=locs,
                          group = combined_data$time_step)

spde0 = inla.spde2.pcmatern(mesh.dom, alpha = 2,
                            prior.range=c(250, 0.01),  
                            prior.sigma=c(1, 0.01),
                            constr = TRUE)

Field.pf = inla.spde.make.index("Field.pf", 
                               spde0$n.spde,
                               n.group=k)

pf.lst = list(c(Field.pf, 
                list(intercept1 = 1)), 
                list(time_step1 = combined_data[,"time_step"],
                     time_step2 = combined_data[,"time_step"])) 

pf.stk = inla.stack(data = list(Y = cbind(combined_data$obs, NA)),
                                A = list(A.pf, 1), 
                          effects = pf.lst,   
                              tag = "pf.0")

```

### Estimate
```{r}
A.est = inla.spde.make.A(mesh.dom, 
                         alpha = 2,
                         loc=locs,
                         group = combined_data$time_step)

Field.est = inla.spde.make.index("Field.est",
                                 spde0$n.spde,
                                 n.group=k)

Field.est.c = inla.spde.make.index("Field.est.c", 
                                   spde0$n.spde,
                                   n.group=k)

est.lst = list(c(Field.est,
                 Field.est.c,
                 list(intercept2 = 1)), 
                 list(pred_var_14 = combined_data[,"pred_var_14"],
                      pred_var_15 = combined_data[,"pred_var_15"],
                      NN = combined_data[,"NN"],
                      time_step1 = combined_data[,"time_step"],
                      time_step2 = combined_data[,"time_step"]))

est.stk = inla.stack(data = list(Y = cbind(NA, combined_data$obs),
                                 e = combined_data$host_pop),
                                 A = list(A.est, 1), 
                           effects = est.lst,   
                               tag = "est.0")



joint.stk = inla.stack(pf.stk, est.stk)
```

## Formula  
```{r}
pcprior1 = list(prec = list(prior="pc.prec", param = c(1, 0.01))) 
hc1 = list(theta = list(prior = 'normal', param = c(0, 10)))
ctr.g = list(model = 'iid', hyper = hc1)

Formula.1 = Y ~ -1 + intercept1 + 
                   intercept2 +
          				f(Field.pf,
          				  model=spde0,
          				  group = Field.pf.group, 
                            control.group=ctr.g) +
                  f(Field.est,
                    copy = "Field.pf", 
          				  group = Field.est.group, 
                            fixed = FALSE,
                            hyper = hc1) + 
         				  f(NN,   
                    model="rw1", 
                    constr=TRUE,
         				    replicate = time_step1,
                    scale.model=TRUE,
         				    hyper=pcprior1) +
                  pred_var_14 + pred_var_15 
```

# Run Model
```{r}
#theta1 = Model.pf$internal.summary.hyperpar$mean
theta1 = c(4.597875, 4.474335, -1.232526, 0.165949, 2.538948, 5.608809, 1.867923)   


Model.demo <- inla(Formula.1, 
      				 num.threads = 12,
      				 data = inla.stack.data(joint.stk), 
      				 family = c("gaussian", "poisson"), 
      				 verbose = TRUE,
      				 E = inla.stack.data(joint.stk)$e,
      				 control.fixed = list(prec = 1, prec.intercept=1), 
      				 control.predictor = list(
      										A = inla.stack.A(joint.stk), 
      										compute = TRUE, 
      										link = 1), 
      				 #control.mode = list(restart = TRUE, theta = theta1),
      				 control.inla = list(strategy="adaptive", 
      									 int.strategy = "eb"),
      				 control.compute=list(dic = TRUE, cpo = TRUE, waic = TRUE)) 				  

summary(Model.demo) 
save(list=c("Model.demo"), file=here("assets/test.RData"), version = 2)








```





